### ISSUE TITLE
Сценарии

### ISSUE THREAD

**Issue by AkhmadBabaev** [WisestKAA/FSD-front-4th-tsk#13]
https://github.com/WisestKAA/FSD-front-4th-tsk/blob/2e001c14edb7b1c441ac96a8cf20c71bfc2141be/src/plugin/view/CurrentValueWrapper/CurrentValueWrapper.ts#L87-L112

Постарайся отрефакторить данный участок кода и в целом пройтись по проекту на предмет слишком скомканного кода, сложно читать (

**Comment by AkhmadBabaev** [comment]
https://github.com/WisestKAA/FSD-front-4th-tsk/blob/2e001c14edb7b1c441ac96a8cf20c71bfc2141be/src/plugin/presenter/Presenter.ts#L94-L101

Старайся избегать многоуровневой вложенности if, пересмотри условия, может где-то можно вынести часть функционала в методы.

**Comment by AkhmadBabaev** [comment]
https://github.com/WisestKAA/FSD-front-4th-tsk/blob/2e001c14edb7b1c441ac96a8cf20c71bfc2141be/src/plugin/presenter/Presenter.ts#L64-L77

Думаю будет лучше держать методы максимально изолированными от всего вокруг поэтому в приоритете модификатор private, вместо protected, а protected используй когда в этом есть четкая необходимость.

**Comment by AkhmadBabaev** [comment]
https://github.com/WisestKAA/FSD-front-4th-tsk/blob/2e001c14edb7b1c441ac96a8cf20c71bfc2141be/src/plugin/presenter/Presenter.ts#L176-L197

Нужно отсортировать методы в следующем порядке, сперва public, затем protected методы и последние private.

**Comment by AkhmadBabaev** [comment]
https://github.com/WisestKAA/FSD-front-4th-tsk/blob/2e001c14edb7b1c441ac96a8cf20c71bfc2141be/src/plugin/view/StyleClasses.ts#L21-L31

Раздели слова в константах нижним подчеркиванием (пример SCALEITEM станет SCALE_ITEM ).

**Comment by AkhmadBabaev** [comment]
https://github.com/WisestKAA/FSD-front-4th-tsk/blob/e402ef1851c57a17c761bf8bcf291528f6d39221/src/plugin/view/SliderLine/SliderLine.ts#L39-L51

Старайся избавляться от вложенности. Как допустим в методе выше можно в блоке if можно выполнить обратное действие выполнить return, а остальной выйдет на уровень выше.

**Comment by WisestKAA** [comment]
#13 [removed nested if in SLiderLine](https://github.com/WisestKAA/FSD-front-4th-tsk/commit/5af9ad83a1679f38bb898093289ff652547c9cd2)
